name: Deploy to Azure on Release

on:
  release:
    types: [published]

permissions:
  contents: read           # Required to checkout code
  deployments: write       # Required for deployment actions
  id-token: write          # Required if using OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip project
      run: zip -r app.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: web-app-python
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.zip
